# Site settings
title: Nate Vick
email: nate.vick@ilcoud.com
description: > # this means to ignore newlines until "baseurl:"
  My place to talk about code, life, and random tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: natron99
github_username: nvick

# Build settings
markdown: kramdown
